### ISSUE TITLE
Calculation of mean

### ISSUE THREAD

**Issue by nbharaths** [Han-JD/GRU-D#1]
Aren't you calculating mean over the whole dataset? When you should be doing it over only train?

**Comment by Han-JD** [comment]
Sorry, there was a mistake. I update the input value at mean calculation. While testing it, I got better results.

In short, you just have to add following part before mean calculation.

```
train_proportion = 0.8
train_index = int(all_x_add.shape[1] * train_proportion)
train_x = all_x_add[:, :train_index]
train_x.shape
```

and put train_x to the get_mean like this.

```
x_mean = get_mean(train_x)
print(x_mean)
print(len(x_mean))
```

You will see some changes.

Thanks!
